// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruprnmksvuksywwlnozq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1cHJubWtzdnVrc3l3d2xub3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzAzNDEsImV4cCI6MjA2NzEwNjM0MX0.1CYkD99pOGvj4zVT0dXuCQGSsT9a00IUvpxZzaC9_zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});